# Generated by Django 4.2.2 on 2023-07-19 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tbl_user',
            table='tbl_user',
        ),
    ]
